/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Copyright (c) 2026 sulfurLabs
 *
 * PROJECT: sulfurOS
 * FILE: sys/input.h
 *
 */

#ifndef _SYS_INPUT_H
#define _SYS_INPUT_H

#include <stdint.h>

typedef enum {
    INPUT_EV_KEY = 0,
    INPUT_EV_REL,
    INPUT_EV_ABS,
} input_event_type_t;

#define INPUT_REL_X 0
#define INPUT_REL_Y 1
#define INPUT_BTN_LEFT 0x110
#define INPUT_BTN_RIGHT 0x111
#define INPUT_BTN_MIDDLE 0x112

/* Stable mirror of the kernel input keycode ABI. Keep new values appended. */
typedef enum {
    INPUT_KEY_NONE=0, INPUT_KEY_ESC,
    INPUT_KEY_1,INPUT_KEY_2,INPUT_KEY_3,INPUT_KEY_4,INPUT_KEY_5,
    INPUT_KEY_6,INPUT_KEY_7,INPUT_KEY_8,INPUT_KEY_9,INPUT_KEY_0,
    INPUT_KEY_MINUS,INPUT_KEY_EQUAL,INPUT_KEY_BACKSPACE,INPUT_KEY_TAB,
    INPUT_KEY_Q,INPUT_KEY_W,INPUT_KEY_E,INPUT_KEY_R,INPUT_KEY_T,
    INPUT_KEY_Y,INPUT_KEY_U,INPUT_KEY_I,INPUT_KEY_O,INPUT_KEY_P,
    INPUT_KEY_LBRACKET,INPUT_KEY_RBRACKET,INPUT_KEY_ENTER,INPUT_KEY_LCTRL,
    INPUT_KEY_A,INPUT_KEY_S,INPUT_KEY_D,INPUT_KEY_F,INPUT_KEY_G,
    INPUT_KEY_H,INPUT_KEY_J,INPUT_KEY_K,INPUT_KEY_L,
    INPUT_KEY_SEMICOLON,INPUT_KEY_APOSTROPHE,INPUT_KEY_GRAVE,
    INPUT_KEY_LSHIFT,INPUT_KEY_BACKSLASH,
    INPUT_KEY_Z,INPUT_KEY_X,INPUT_KEY_C,INPUT_KEY_V,INPUT_KEY_B,
    INPUT_KEY_N,INPUT_KEY_M,INPUT_KEY_COMMA,INPUT_KEY_DOT,INPUT_KEY_SLASH,
    INPUT_KEY_RSHIFT,INPUT_KEY_KP_ASTERISK,INPUT_KEY_LALT,INPUT_KEY_SPACE,
    INPUT_KEY_CAPSLOCK,INPUT_KEY_DELETE,
    INPUT_KEY_UP,INPUT_KEY_DOWN,INPUT_KEY_LEFT,INPUT_KEY_RIGHT,
    INPUT_KEY_HOME,INPUT_KEY_END,INPUT_KEY_PAGEUP,INPUT_KEY_PAGEDOWN,
    INPUT_KEY_INSERT,INPUT_KEY_RCTRL,INPUT_KEY_RALT,
    INPUT_KEY_KP_ENTER,INPUT_KEY_KP_SLASH,
    INPUT_KEY_F1,INPUT_KEY_F2,INPUT_KEY_F3,INPUT_KEY_F4,INPUT_KEY_F5,
    INPUT_KEY_F6,INPUT_KEY_F7,INPUT_KEY_F8,INPUT_KEY_F9,INPUT_KEY_F10,
    INPUT_KEY_F11,INPUT_KEY_F12,
} input_keycode_t;

typedef struct {
    input_event_type_t type;
    uint16_t code;
    int32_t value;
    uint8_t modifiers;
} input_event_t;

#define INPUT_MOD_SHIFT (1 << 0)
#define INPUT_MOD_CTRL (1 << 1)
#define INPUT_MOD_ALT (1 << 2)
#define INPUT_MOD_CAPS (1 << 3)

#endif
